### Login correcto
POST http://127.0.0.1:8001/login
Content-Type: application/json

{
    "usuario": "admin",
    "contrasena": "admin123"
}

### Login con gestion humana
POST http://127.0.0.1:8001/login
Content-Type: application/json

{
    "usuario": "gestionhumana",
    "contrasena": "gh123"
}

### Login incorrecto
POST http://127.0.0.1:8001/login
Content-Type: application/json

{
    "usuario": "admin",
    "contrasena": "incorrecta"
}

### Logout
POST http://127.0.0.1:8001/logout
Content-Type: application/json

{
    "token": "TOKEN_AQUI"
}

### Validar token
GET http://127.0.0.1:8001/validar-token
Authorization: TOKEN_AQUI